# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shoulda-addons}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Meyer"]
  s.date = %q{2011-02-15}
  s.description = %q{Some awesome addons for Shoulda to benchmark tests, or to get nicer output than just a dot, because what the dot?}
  s.email = %q{meyer@paperplanes.de}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "lib/shoulda_addons.rb",
    "lib/shoulda_benchmark.rb",
    "lib/shoulda_list_runner.rb"
  ]
  s.homepage = %q{http://github.com/mattmatt/shoulda-addons}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Neat addons for Shoulda, because Shoulda is neat.}
  s.test_files = [
    "test/shoulda_benchmark_minitest_test.rb",
    "test/shoulda_benchmark_test_unit_1x_test.rb",
    "test/shoulda_benchmark_test_unit_2x_test.rb",
    "test/shoulda_list_runner_minitest_test.rb",
    "test/shoulda_list_runner_test_unit_1x_test.rb",
    "test/shoulda_list_runner_test_unit_2x_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

